name: Cesium for Unreal Samples
on: [push]
jobs:
  Package:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Unreal Engine
        uses: ./.github/actions/install-unreal-windows
        with:
          unreal-engine-zip: "s3://cesium-unreal-engine/5.5.0/UE_5.5.zip"
          unreal-program-name: "UE_5.5"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Set environment variables
        run: |
          $ENV:SAMPLES_VERSION=$env:GITHUB_REF_NAME
          $ENV:SAMPLES_PACKAGE_NAME="CesiumForUnrealSamples-${ENV:SAMPLES_VERSION}"

          # Make the package name available to subsequent steps
          echo "SAMPLES_PACKAGE_NAME=${ENV:SAMPLES_PACKAGE_NAME}" >> $ENV:GITHUB_ENV
      - name: Package Project
        run: |
          cd "D:/Program Files/Epic Games/UE_5.4/Engine/Build/BatchFiles"
          & "D:/Program Files/Epic Games/UE_5.4/Engine/Build/BatchFiles/RunUAT.bat" ZipProjectUp -nocompileeditor -project="${ENV:GITHUB_WORKSPACE}/" -install="${ENV:GITHUB_WORKSPACE}/${ENV:SAMPLES_PACKAGE_NAME}".zip -nocompile
      - name: Extract built package
        run: |
          # Unzip the package ZIP so that it's not a ZIP inside a ZIP when published as a GitHub artifact.
          mkdir extracted_package
          7z x "${ENV:GITHUB_WORKSPACE}/${ENV:SAMPLES_PACKAGE_NAME}.zip" "-o${ENV:GITHUB_WORKSPACE}/extracted_package"
      - name: Publish project package artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SAMPLES_PACKAGE_NAME}}.zip
          path: extracted_package
